# Generated by Django 4.0.4 on 2022-08-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_reseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='author',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
