# Generated by Django 4.0.4 on 2022-08-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_review_remove_reseña_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='date_update',
            new_name='date_updated',
        ),
    ]
