# Generated by Django 4.0.4 on 2022-08-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0012_post_post_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
