# Generated by Django 4.0.4 on 2022-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_delete_curso_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
