# Generated by Django 4.0.5 on 2022-07-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_rename_materia_profesor_profesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
