# Generated by Django 4.0.4 on 2022-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Reviews', max_length=255),
        ),
    ]
